export const dialogs = [
    {
        id: "uploadFile",
        title: "Select Files to Upload",
        inputType: "file",
        isForm: true,
        formMethod: "post",
        formAction: "/upload",
        cancelBtn: "CANCEL",
        submitBtn: "UPLOAD",
    },
    {
        id: "createNewFolder",
        title: "Create Folder",
        inputType: "text",
        isForm: false,
        inputLabel: "Give this folder a name:",
        placeholder: "Folder Name",
        cancelBtn: "CANCEL",
        submitBtn: "CREATE",
    },
    {
        id: "renameFolder",
        title: "Rename Folder",
        inputType: "text",
        isForm: false,
        inputLabel: "Give this folder a New name:",
        placeholder: "New Folder Name",
        cancelBtn: "CANCEL",
        submitBtn: "RENAME",
    },
    {
        id: "deleteFolder",
        title: "Delete Folder",
        inputType: "text",
        isForm: false,
        inputLabel:
            "To confirm deletion, type ' DELETE ' in the text input field.",
        placeholder: "DELETE",
        cancelBtn: "CANCEL",
        submitBtn: "DELETE",
    },
    {
        id: "deleteFile",
        title: "Delete File",
        inputType: "text",
        isForm: false,
        inputLabel:
            "To confirm deletion, type ' DELETE ' in the text input field.",
        placeholder: "DELETE",
        cancelBtn: "CANCEL",
        submitBtn: "DELETE",
    },
];
